# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and deploy to firebase
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Stage Deploy

on:
  push:
    branches: [ "stage" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - run: cd './frontend'
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: cd '../'
    - run: firebase deploy
